### ISSUE TITLE
Garage door single button and closing timer

### ISSUE THREAD

**Issue by oliverjtowers** [jmbwell/GarageDoorOpener#1]
Hi, your code is really amazing!! I am trying to perform an implementation based on your code for a single button (only opening), with  a closing timer. Do you know how to do it ?

**Comment by jmbwell** [comment]
If I understand you correctly, I think you’d have to make several changes. It’s a different approach. I suspect you’d need to start with a global variable for your timer. Whenever the target state changes, set it to the current time in milliseconds. In the loop, check the difference between the global variable and the current time in milliseconds, to get the time elapsed. Whenever the time elapsed is greater than your open/close period and the target state and current state are different, then set the current state to the target state. Something like that. And then you’d have to take out all the stuff about the sensors. Have fun, and good luck!
